### ISSUE TITLE
make only uses default python

### ISSUE THREAD

**Issue by aburrell** [timduly4/pyglow#100]
The make file for the models isn't set up so that you can run each of the commands separately.  This is a problem when your computer's default python command isn't the one you want to use for this installation.  This could be addressed by breaking out the different make commands into separate bits and using `all` for the combo, instead of having `source` be a combo as well, and adding documentation so that the user knows they may need to run the download command themselves.  Alternatively, this could be addressed by allowing the user to specify the python version through the command line: 

```
make -C src/pyglow/models source PYTHON=/opt/anaconda3/bin/python
```

**Comment by aburrell** [comment]
This is also an issue for the f2py commands.

**Comment by timduly4** [comment]
I don't like having the user run multiple `make` commands.  I prefer running `make -C src/pyglow/models source PYTHON=/opt/anaconda3/bin/python`

> This is also an issue for the f2py commands.

Where does this occur?

**Comment by aburrell** [comment]
The f2py commands occur for all of the fortran models.  It should probably be defined in the top level make and sent down, same as the python command: `make -C src/pyglow/models source PYTHON=/opt/anaconda3/bin/python F2PY=/opt/local/bin/f2py`

**Comment by timduly4** [comment]
@aburrell Can you make a PR for this?

**Comment by aburrell** [comment]
Sure, but I won't get to it for a while.

**Comment by aburrell** [comment]
Made changes, but can't figure out how to push the branch here.  Working on a remote system, so not my normal set up.

**Comment by timduly4** [comment]
Here's instructions for making a PR: https://help.github.com/en/articles/creating-a-pull-request

**Comment by aburrell** [comment]
Yeah, I had looked those and several other help guides up and couldn't get it to work.  Found a few links to known git bugs before I ran out of time to track down what the real problem was.  I'll have another go in a while, but probably not for the next 2 weeks.

**Comment by timduly4** [comment]
I'll close for now, feel free to reopen when you can submit a PR.
