### ISSUE TITLE
issue installing pyglow

### ISSUE THREAD

**Issue by adoneill03** [timduly4/pyglow#104]
My installation seems to fail when I am downloading and converting the models from Fortran.

I'm able to clone everything and to the best of my knowledge I have all the dependencies satisfied. I believe I am using python 2.7. I have gfortran-8 installed and receive the following output:

Downloading: http://irimodel.org/indices/apf107.dat to ./dl_models/iri16/apf107.dat
Downloading: http://irimodel.org/indices/ig_rz.dat to ./dl_models/iri16/ig_rz.dat
cp ./f2py/igrf11/* ./dl_models/igrf11/
cd ./dl_models/igrf11/; make source
make[1]: Entering directory '/home/a/pyglow/src/pyglow/models/dl_models/igrf11'
make patch_igrf11;
make[2]: Entering directory '/home/a/pyglow/src/pyglow/models/dl_models/igrf11'
patch igrf11.f -i igrf11.patch -o igrf11_modified.f
patching file igrf11_modified.f (read from igrf11.f)
make[2]: Leaving directory '/home/a/pyglow/src/pyglow/models/dl_models/igrf11'
make sig;
make[2]: Entering directory '/home/a/pyglow/src/pyglow/models/dl_models/igrf11'
f2py -m igrf11py -h sig_file.pyf igrf11_modified.f only: igrf11syn : | tee out1
/bin/sh: 1: f2py: not found
make[2]: Leaving directory '/home/a/pyglow/src/pyglow/models/dl_models/igrf11'
make patch_sig;
make[2]: Entering directory '/home/a/pyglow/src/pyglow/models/dl_models/igrf11'
patch sig_file.pyf -i sig.patch -o sig_file_patched.pyf
patching file sig_file_patched.pyf (read from sig_file.pyf)
Hunk #1 FAILED at 13.
1 out of 1 hunk FAILED -- saving rejects to file sig_file_patched.pyf.rej
Makefile:23: recipe for target 'patch_sig' failed
make[2]: *** [patch_sig] Error 1
make[2]: Leaving directory '/home/a/pyglow/src/pyglow/models/dl_models/igrf11'
Makefile:29: recipe for target 'source' failed
make[1]: *** [source] Error 2
make[1]: Leaving directory '/home/a/pyglow/src/pyglow/models/dl_models/igrf11'
Makefile:23: recipe for target 'source' failed
make: *** [source] Error 2
make: Leaving directory '/home/a/pyglow/src/pyglow/models' 

after running:

$ cd pyglow/
$ make -C src/pyglow/models source
$ python3 setup.py install --user

**Comment by timduly4** [comment]
@adoneill03 , it looks like you are missing `f2py`:

```
~ $ which f2py
/Users/duly/Library/Python/3.7/bin/f2py
```
I believe you can install it via numpy:

```
$ pip install numpy --user
```

**Comment by adoneill03** [comment]
I believe that I have it installed

> which f2py
> /home/a/.local/bin/f2py

**Comment by timduly4** [comment]
That's strange, as the error refers to you not having f2py:
```
/bin/sh: 1: f2py: not found
```

**Comment by adoneill03** [comment]
inspecting /.local/bin there are three versions of f2py:
f2py, f2py2, f2py2.7 
Could that be the problem?

**Comment by timduly4** [comment]
I don't believe so-- you might try updating/ reinstalling your numpy
package to reinstall f2py

**Comment by adoneill03** [comment]
So i defined an environment variable as 
`f2py=/home/a/.local/bin/f2py`  
Which got me further. The next issue that came up that it cant find my gfortran installation

      Reading file 'sig_file_patched.pyf' (format:free)
Post-processing...
        Block: igrf11py
                        Block: igrf11syn
Post-processing (stage 2)...
Building modules...
        Building module "igrf11py"...
                Constructing wrapper function "igrf11syn"...
                  x,y,z,f = igrf11syn(isv,date,itype,alt,colat,elong)
        Wrote C/API module "igrf11py" to file "/tmp/tmpXSpaoN/src.linux-x86_64-2.7/igrf11pymodule.c"
  adding '/tmp/tmpXSpaoN/src.linux-x86_64-2.7/fortranobject.c' to sources.
  adding '/tmp/tmpXSpaoN/src.linux-x86_64-2.7' to include_dirs.
copying /home/a/.local/lib/python2.7/site-packages/numpy/f2py/src/fortranobject.c -> /tmp/tmpXSpaoN/src.linux-x86_64-2.7
copying /home/a/.local/lib/python2.7/site-packages/numpy/f2py/src/fortranobject.h -> /tmp/tmpXSpaoN/src.linux-x86_64-2.7
build_src: building npy-pkg config files
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
customize Gnu95FCompiler
Could not locate executable gfortran
Could not locate executable f95
customize IntelFCompiler
Could not locate executable ifort
Could not locate executable ifc
customize LaheyFCompiler
Could not locate executable lf95
customize PGroupFCompiler
Could not locate executable pgfortran
customize AbsoftFCompiler
Could not locate executable f90
Could not locate executable f77
customize NAGFCompiler
customize VastFCompiler
customize CompaqFCompiler
Could not locate executable fort
error: extension 'igrf11py' has Fortran sources but no Fortran compiler foundcustomize IntelItaniumFCompiler
Could not locate executable efort
Could not locate executable efc
customize IntelEM64TFCompiler
customize GnuFCompiler
Could not locate executable g77
customize G95FCompiler
Could not locate executable g95
customize PathScaleFCompiler
Could not locate executable pathf95
customize NAGFORCompiler
Could not locate executable nagfor
don't know how to compile Fortran code on platform 'posix'
warning: build_ext: f77_compiler=None is not available.

building 'igrf11py' extension

make[2]: Leaving directory '/home/a/pyglow/src/pyglow/models/dl_models/igrf11'
make[1]: Leaving directory '/home/a/pyglow/src/pyglow/models/dl_models/igrf11'
rsync: link_stat "/home/a/pyglow/src/pyglow/models/dl_models/igrf11/igrf11py*so" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 23

**Comment by timduly4** [comment]
It doesn't look like your gfortran can be found. What outputs from $ which
gfortran?

**Comment by adoneill03** [comment]
reinstalled gfortran and that seemed to solve it
