### ISSUE TITLE
Coordinate System

### ISSUE THREAD

**Issue by panagiotispir** [timduly4/pyglow#114]
Not an Issue but just a question.
I would like to inform what exactly coordinate system is pyglow using?
I saw a coord.py file which includes some functions about coordinates, but I can't underastant which system exactly pyglow using.
Sorry for issue creation, I didn't find another way to contact with you.
thanks in advance

**Comment by bharding512** [comment]
x = East
y = North
z = Up

I guess you'd call this local geographic. The fact that this is not obvious is because we don't have a good API (which is issue #24 )

**Comment by panagiotispir** [comment]
Sorry about reopening this issue.
According to fortan code of models, all of them have the ability to run on different coordinate systems such as GEO(geographic) or GEOD(geodetic) or MAG(geomagnetic).
I tried to read pyglow code to understand where pyglow does this selection, but I couldn't find it. 
Because your answer wasn't 100% clear for me, I would like to ask you again. When I create the point for pyglow, am I using GEO coordinates for all models(IRI,HWM, MSISE,IGRF) that pyglow implements?
