### ISSUE TITLE
JMag parameter in IRI model

### ISSUE THREAD

**Issue by pavel9609** [timduly4/pyglow#118]
Why, when invoking the iri model, is it not possible to specify the jmag key by default? I solved my problem by changing the function run_iri and the iri module. I wanted to know if there are reasons why this parameter is not available by default?

**Comment by timduly4** [comment]
The intention behind pyglow was to be able to call IRI while abstracting away the majority of parameters.  If you'd like to include flexibility with an optional jmag parameter, create a PR and we'll look at it.
