### ISSUE TITLE
Naming in IGRF

### ISSUE THREAD

**Issue by ghost** [timduly4/pyglow#119]
Hi!
I think it would be beneficial if the field **dip** inside the method **run_igrf** would be redefined from 
`dip = 180./np.pi * np.arctan2(z,h)`
to
`inc = 180./np.pi * np.arctan2(z,h)`
and also adding the following lines inside the same method
`dip = 180./np.pi * np.arctan2(z,2*h)`
`self.inc=inc`
This would align the naming with other references like Laundal ad Richmond 2016.

**Comment by bharding512** [comment]
Thanks for pointing this out! +1 for Laundal and Richmond (2017?) being a standard source for definitions.

I think the disconnect here is between dip *angle* and dip *latitude*. The equation you give I think is from their Eq 22, which is for dip *latitude*

![image](https://user-images.githubusercontent.com/8883135/65170637-f7de3900-d9fd-11e9-9547-b545d07a4c96.png)

Dip angle is simply the angle a compass would make with respect to z, which is the same but without the "2".

Now, whether pyglow should start to include magnetic coordinates is a different question. I'm tempted to say we should stay out of that game, and leave it to the pros like apexpy (https://github.com/aburrell/apexpy)

I'll leave this issue for you to close, if you think it solves the problem.

**Comment by bharding512** [comment]
Closing since it's been 2 years
