### ISSUE TITLE
the 'jf' in 'iri.py' has difference from IRI-2016 standard version. 

### ISSUE THREAD

**Issue by zzyztyy** [timduly4/pyglow#124]
The jf Fortran index 39 is False and 40 is True in standard version correspond to the AMTB-model. But in iri.py, the jf Fortran index 39 is set as True correspond to (M3000)F2, an old model. Some investigates indicate the  Shubin-COSMIC model performs better, which means the index 39 and 40 should be both set as False. I suggest to apply the AMTB-model to consist with the IRI web.
Another option is called as 'F-peak storm model', which set as 'on' in IRI web but 'off' in the Fortran code. In pyglow, it is 'off'. It doesn't matter during magnetic quiet period. But when the magnetic storm occurs, the result would be more accurate if it is 'on'.
The change can be done or not, but the difference should be indicated for better using.

**Comment by timduly4** [comment]
Please submit a PR so we can see what this looks like.

**Comment by ramazanatici** [comment]
I want to run the IRI model in python, but i don't run IRI model. Readme file is a little complex. Can you write step by step how can i run this model? Sincerely yours... 

Ramazan ATICI
Mus Alparslan University, TURKEY

**Comment by bharding512** [comment]
Closing, but feel free to reopen if this is still valid.
