### ISSUE TITLE
issue installing pyglow 

### ISSUE THREAD

**Issue by JimPlayboy** [timduly4/pyglow#127]
the problem occurred after the command " make -C src/pyglow/models source". the  problem is similar to issue 104. but the numpy is newly updated to 1.18.1 and f2py.exe is not missing. i tried to add the f2py to my environment variable, but that did not solve the problem.

i find out that there is no "sig_file.pyf" in the folder 'src/pyglow.models/dl_models/igrf11/'. Could that be the problem?

make[1]: Entering directory 'C:/Users/Administrator/Desktop/pyglow/src/pyglow/models/dl_models/igrf11'
make patch_igrf11;
make[2]: Entering directory 'C:/Users/Administrator/Desktop/pyglow/src/pyglow/models/dl_models/igrf11'
patch igrf11.f -i igrf11.patch -o igrf11_modified.f
patching file igrf11_modified.f (read from igrf11.f)
make[2]: Leaving directory 'C:/Users/Administrator/Desktop/pyglow/src/pyglow/models/dl_models/igrf11'
make sig;
make[2]: Entering directory 'C:/Users/Administrator/Desktop/pyglow/src/pyglow/models/dl_models/igrf11'
f2py -m igrf11py -h sig_file.pyf igrf11_modified.f only: igrf11syn : | tee out1
make[2]: Leaving directory 'C:/Users/Administrator/Desktop/pyglow/src/pyglow/models/dl_models/igrf11'
make patch_sig;
make[2]: Entering directory 'C:/Users/Administrator/Desktop/pyglow/src/pyglow/models/dl_models/igrf11'
patch sig_file.pyf -i sig.patch -o sig_file_patched.pyf
patching file sig_file_patched.pyf (read from sig_file.pyf)
Hunk #1 FAILED at 13.
1 out of 1 hunk FAILED -- saving rejects to file sig_file_patched.pyf.rej
Makefile:23: recipe for target 'patch_sig' failed
make[2]: *** [patch_sig] Error 1
make[2]: Leaving directory 'C:/Users/Administrator/Desktop/pyglow/src/pyglow/models/dl_models/igrf11'
Makefile:29: recipe for target 'source' failed
make[1]: *** [source] Error 2
make[1]: Leaving directory 'C:/Users/Administrator/Desktop/pyglow/src/pyglow/models/dl_models/igrf11'
Makefile:23: recipe for target 'source' failed
make: *** [source] Error 2
make: Leaving directory 'C:/Users/Administrator/Desktop/pyglow/src/pyglow/models'

**Comment by timduly4** [comment]
Can you provide the full output?

**Comment by JimPlayboy** [comment]
the output in the folder 'src\pyglow\models\dl_models\igrf11' is:

[igrf11.zip](https://github.com/timduly4/pyglow/files/4310132/igrf11.zip)

**Comment by JimPlayboy** [comment]
i am working on a windows 10 system. the gfortran version is 6.3.0. the python version is 3.8.2. GNU bash version 4.4.23(1)-release (x86_64-pc-msys)
i had trouble downloading the models, so i had created a local server and had modified the makefile.
