### ISSUE TITLE
IRI-2016 not running past 2010

### ISSUE THREAD

**Issue by jklenzing** [timduly4/pyglow#128]
I noticed that something is crashing IRI-2016 for dates past Jan 1 2010.  This is occurring both on my local computer (Mac) as well as the Travis CI linux setup for pysatMissions, which includes IRI functionality through pyglow.

If I run the following, I get the expected parameters in `pt`.
```
import pyglow
import datetime as dt
pt = pyglow.Point(dt.datetime(2009,12,31), 0, 0, 400)  
pt.run_iri()
```
However, if the time is set to dt.datetime(2010, 1, 1) or later, ipython and pytest will crash without further output.

If I use the `version=2012` flag, this runs as expected, with the obvious warnings for years past 2015.

Local setup: 
python 3.7.3
Mac OS X 10.15.4
numpy 1.19.0
scipy 1.4.1

**Comment by bharding512** [comment]
Verified using:
python 3.7.1
CentOS 7
numpy 1.19.2
scipy 1.5.2
IRI-16 as of 2020.08 09/16/20 (with modification described here: https://github.com/timduly4/pyglow/issues/130#issuecomment-706464688)

**Comment by bharding512** [comment]
I tried compiling pyglow using an older version of IRI-16:

- 2016.15 05/07/18: Works fine
- 2020.08 09/16/20: Crashes post-2010

So some update of IRI broke pyglow post-2010 somehow. It's hard to narrow it down further since I can't find old versions of IRI online (I happened to have 2016.15 05/07/18 locally saved).

**Comment by pmreyes2** [comment]
PR #131 fixes this problem by adding the correct list of iri 2016 files in the setup.py file. Essentially file dgrf2015.dat was missing in the installed files. The PR just passed the tests, and hopefully can be merged to master before we include pyglow in our upcoming [resen-core](https://resen-core.readthedocs.io) release.
