### ISSUE TITLE
IRI-16 install failure

### ISSUE THREAD

**Issue by bharding512** [timduly4/pyglow#130]
IRI-16 installation seems broken, which is crashing the overall pyglow installation. This was tested on Linux and Mac. Can anyone verify this? For me:

`python3 setup.py install`

fails here:

```
gfortran:f77: build/src.macosx-10.14-x86_64-3.8/src/pyglow/models/dl_models/iri16/iri16py-f2pywrappers.f
src/pyglow/models/dl_models/iri16/irifun.for:8100:22:

          sunx=sign(99,flat)
                      1
Error: 'b' argument of 'sign' intrinsic at (1) must be the same type and kind as 'a'
error: Command "/usr/local/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops -Ibuild/src.macosx-10.14-x86_64-3.8/build/src.macosx-10.14-x86_64-3.8/src/pyglow/models/dl_models/iri16 -I/Users/bharding/envs/env_pyglowtest/lib/python3.8/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/Users/bharding/envs/env_pyglowtest/include -I/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c -c src/pyglow/models/dl_models/iri16/irifun.for -o build/temp.macosx-10.14-x86_64-3.8/src/pyglow/models/dl_models/iri16/irifun.o -std=legacy -w -O2 -fbacktrace -fno-automatic -fPIC" failed with exit status 1
```

I tried using an older version of IRI-16 (_2016.24 08/29/18_) which I had laying around. When I replaced the entire src/pyglow/models/dl_models/iri16 folder with this older version, the installation worked fine.

Does this mean that there is an upstream problem with the latest IRI-16? (_2020.08 09/16/20_)

If so, we should figure out exactly which version broke the pyglow install: 

> C 2016.20 04/23/18 Versioning now based on year of major releases
> C 2016.21 04/25/18 Moved secni to Te calculation .......... C. Vasly
> C 2016.21 04/25/18 Deleted arrays ddo and d2o; not used ... C. Vasly
> C 2016.22 08/23/18 CNEW! B0-Gulyaeva option revised .... T. Gulyaeva
> C 2016.23 08/27/18 Moved FIRI option under ELDE calc ..... P. Sultan
> C 2016.23 08/27/18 3-h ap,kp available even if storm models are off
> C 2016.23 08/27/18 daily ap avail. even if F10.7din or F10.7_81in
> C 2016.24 08/29/18 user input for HNEA and HNEE if jf(45) jf(46)
> C 2016.25 06/11/19 comments for OARR and output incl HNEA and HNEE
> C 2020.01 07/03/19 changed argmax to 87.3 (consistent with IDL)
> C 2020.01 07/03/19 itopn=1 now with PF10.7 correction
> C 2020.02 07/19/19 itopn=1 cor option, itopn=3 cor2 option
> C 2020.03 07/29/19 added 'endif' itopn=3 and declared a01(2,2)        
> C 2020.04 08/05/19 itopn=3 requires itopn=1, BLO11 change        
> C 2020.05 01/16/20 ion composition topside if h.ge.300km
> C 2020.06 06/15/20 Den_NO=0.0,rn=0.0 before CHEMION ---- M. Hausman
> C 2020.06 06/15/20 IF(..hcor1) after IF(itopn....) ..... M. Hausman 
> C 2020.07 08/24/20 changed if(sam_moye ...) ------------ A. Rodland
> C 2020.07 08/24/20 FELDCOF only when new date ---------- A. Rodland             
> C 2020.08 09/16/20 added HPOL for topside COR2 option
> C 2020.08 09/16/20 not comp'd oarr variables: -1 or -100 for lati
> C 2020.08 09/16/20 jf(47) for CGM computation on/off; lati>25

**Comment by bharding512** [comment]
As per advice from Dieter Bilitza:

In irifun.for, find the line:
sunx=sign(99,flat)
change to
sunx=sign(99.0,flat)

This solves the problem for me.  He indicated that this will be updated in a future IRI-16 release.

I'll keep this issue open for now. We can close it when IRI is updated.

**Comment by jhughes-space** [comment]
I just pulled, and the sunx line already had the decimal. It will install, but iri2016 wont run past 2010

**Comment by bharding512** [comment]
Thanks @jhughes-space, I now see that IRI-16 was updated on 10/12/2020, which fixes this issue. Closing this....

The issue about running past 2010 is #128. Haven't figured out what's causing that yet.
