### ISSUE TITLE
ValueError: Must supply ap for HWM14

### ISSUE THREAD

**Issue by rafaelmesquita1987** [timduly4/pyglow#133]
Running on Ubuntu, Jupyter Notebook, Python3:

%%%%%%%
def DTtoUNIX(UTC):
    import time
    SKUNIXTim = []
    for i in range(np.size(UTC)):
        SKUNIXTim.append(time.mktime(UTC[i].timetuple()))
    SKUNIXTim = np.array(SKUNIXTim)
    return SKUNIXTim

timestamp = DTtoUNIX([datetime(2015,1,1), datetime(2018,1,1)])
print(timestamp)
timestamps = np.arange(1.4200884e+09,1.5147828e+09,86400*2)
msisalts = np.arange(80,500.1,1)

lat, lon = 0,0
U,V = [],[]
for i in range(np.size(timestamps)):
    auxU, auxV=[],[]
    dt_object = datetime.fromtimestamp(timestamps[i])
    for j in range(np.size(msisalts)):
        pt = pyglow.Point(dt_object, lat, lon, msisalts[j])
        pt.run_hwm(version=2014)
        auxU.append(pt.u) 
        auxV.append(pt.v) 
    U.append(auxU)
    V.append(auxV)
print(np.shape(U))
%%%%%%%%%%%%%%%%%

I get the error: ValueError: Must supply ap for HWM14

Can't figure out why... Any suggestion?

All indices are up to date. Can't quite understand what's going on...

**Comment by bharding512** [comment]
I get the same error. This is issue #121 

It will be a simple fix, but in the meantime, a bandaid like this would work for now:

```
pt = pyglow.Point(dt_object, lat, lon, msisalts[j])
if pt.ap == 0.0:
    pt.ap = -1
pt.run_hwm(version=2014)
```
