### ISSUE TITLE
How can I find codes or library to obtain the Volume Emission Rate of 5577

### ISSUE THREAD

**Issue by cahngkong** [timduly4/pyglow#137]
I have visited the pyglow/test_airglow.py at 9bf2b364aa66e3428a87888115fc3cbd2ab05540 · timduly4/pyglow · GitHub 6 website for a month
I found the codes for 630.0 nm and 777.4 nm   but cannot find codes or library for 557.7 nm airglow.

How can I find it？

**Comment by bharding512** [comment]
pyglow doesn't currently have a green line formula implemented. You can find an example here that has some green line models coded up: https://github.com/bharding512/airglowrsss/blob/master/Python/modules/MIGHTI.py#L312

It uses the WINDII-based empirical model for dayglow from Zhang and Shepherd [2005], and a photochemical model for the three-body nightglow reaction using MSIS concentrations from the Vargas et al. [2007] formulation. It's a research code, so use at your own risk.

**Comment by bharding512** [comment]
Closing since there doesn't seem like anything more to do
