### ISSUE TITLE
Windows Installation on Msys

### ISSUE THREAD

**Issue by Luca-ggmb** [timduly4/pyglow#138]
I have spent ages following the exact instructions given but still cannot get this module to install. I get to the step where in the Msys64 command windows I execute the make command. The command executes correctly but I am thrown several errors(for brevity I am only including one instance of each):

- "Line #77 in iriflip.for:"      INTEGER INEWT         !.. Signifies when the Newton procedure fail"
        updatevars: could not crack entity declaration "inewt!..". Ignoring."

- " patch sig_file.pyf -i sig.patch -o sig_file_patched.pyf
patching file sig_file_patched.pyf (read from sig_file.pyf)
Hunk #1 FAILED at 109.
1 out of 1 hunk FAILED -- saving rejects to file sig_file_patched.pyf.rej
make[2]: *** [Makefile:32: patch_sig] Error 1
make[2]: Leaving directory '/home/ggmb1/pyglow/src/pyglow/models/dl_models/iri12'
make[1]: *** [Makefile:47: source] Error 2
make[1]: Leaving directory '/home/ggmb1/pyglow/src/pyglow/models/dl_models/iri12'
make: *** [Makefile:32: source] Error 2
make: Leaving directory '/home/ggmb1/pyglow/src/pyglow/models' "

Amongst several others which I cannot view in the command window. I have checked several times that all the required modules numpy Fortran etc are installed. Any ideas on resolution or clear steps on Windows installation would be greatly appreciated.
Thanks,Luca

**Comment by bharding512** [comment]
@timduly4 and I have never tried installing on Windows, but there is potentially some useful advice in #8
