### ISSUE TITLE
MSIS link is hanging

### ISSUE THREAD

**Issue by aburrell** [timduly4/pyglow#14]
I'm trying to install pyglow and the MSIS link keeps timing out.  Not sure if this is permanent or not, but might be worth following up.

**Comment by timduly4** [comment]
This is a result of the Fortran file no longer being available from the FTP site:

`ftp://hanna.ccmc.gsfc.nasa.gov/pub/modelweb/atmospheric/msis/nrlmsise00/nrlmsise00_sub.for`

We'll have to find another location to download MSIS...

**Comment by bharding512** [comment]
I emailed the CCMC to let them know. Unfortunately the backup link directly from NRL also appears to be dead.

**Comment by bharding512** [comment]
CCMC said that FTP is "currently unavailable"... no kidding.

If this lasts another day or so, we should just host it at Illinois as a temporary measure. Or, since MSIS00 is not likely to change (I think?), we could just distribute it with pyglow.

**Comment by aburrell** [comment]
An extra-safe measure might be to host it on pyglow, but only use the hosted version if the ftp fails.  More faff, but it provides a safety buffer if you’re away during a model update.

**Comment by timduly4** [comment]
I was always weary of hosting other organizations source code, but if it is unreliable, then I agree: let's just include it with `pyglow`.

**Comment by butala** [comment]
This problem was causing some issues with an automated testing step for another code that depends on pyglow. I took the path suggested above and made a change to host the code locally in the repository and made the resulting required changes.

**Comment by butala** [comment]
Just wanted to add that HWM93 had similar issues (ftp://hanna.ccmc.gsfc.nasa.gov/pub/modelweb/atmospheric/hwm93/ is unavailable). Implemented a similar fix. Kind of a kludgy fix, but I am unsure what else to do when the main source for these models is unavailable.

**Comment by timduly4** [comment]
Thanks, @butala !
