### ISSUE TITLE
Resolved: Please how to fix this problem encountred when installing pyglow

### ISSUE THREAD

**Issue by mkmohamed** [timduly4/pyglow#140]
Hi all,
after installing all Prerequisites i tried to install pyglow with **Individual installation steps:**

BUT when i type make all I have the error below; I will be very grateful if you can help me to install this package:

mk-laptop@mklaptop-HP-EliteBook-840-G3:~/pyglow/src/pyglow/models$ sudo make all[sudo] password for mk-laptop: 
rm -rf *~
rm -rf ./dl_models/hwm93/*
rm -rf ./dl_models/hwm07/*
rm -rf ./dl_models/hwm14/*.pyf
rm -rf ./dl_models/hwm14/out*
rm -rf ./dl_models/hwm14/*.so
rm -rf ./dl_models/igrf11/*
rm -rf ./dl_models/igrf12/*
rm -rf ./dl_models/iri12/*
rm -rf ./dl_models/iri16/*
rm -rf ./dl_models/msis/*
touch ./dl_models/hwm07/dummy.txt
touch ./dl_models/hwm93/dummy.txt
touch ./dl_models/igrf11/dummy.txt
touch ./dl_models/igrf12/dummy.txt
touch ./dl_models/iri12/dummy.txt
touch ./dl_models/iri16/dummy.txt
touch ./dl_models/msis/dummy.txt
python get_models.py
Downloading files for igrf11 at http://www.ngdc.noaa.gov/IAGA/vmod/igrf11.f
Wrote: ./dl_models/igrf11/igrf11.f
Downloading files for igrf12 at http://www.ngdc.noaa.gov/IAGA/vmod/igrf12.f
Wrote: ./dl_models/igrf12/igrf12.f
Downloading files for hwm07 at https://github.com/timduly4/pyglow/raw/master/static/HWM07_all_files.zip
Wrote: ./dl_models/hwm07/HWM07_all_file.zip
unzip ./dl_models/hwm07/HWM07_all_file.zip
Archive:  ./dl_models/hwm07/HWM07_all_file.zip
  inflating: HWM07/apexcord.f90      
  inflating: HWM07/apexgrid.dat      
  inflating: HWM07/checkhwm07.f90    
  inflating: HWM07/dwm07b.f90        
  inflating: HWM07/dwm07b_104i.dat   
  inflating: HWM07/hwm071308e.dat    
  inflating: HWM07/hwm07e.f90        
  inflating: HWM07/makefile.g95      
  inflating: HWM07/makefile.ifort    
  inflating: HWM07/readme.txt        
Downloading files for hwm93 at https://github.com/timduly4/pyglow/raw/master/static/hwm93.f
Wrote: ./dl_models/hwm93/hwm93.f
Downloading files for iri12 at http://spdf.gsfc.nasa.gov/pub/models/iri/iri2012/00_iri2012.tar
http://spdf.gsfc.nasa.gov/pub/models/iri/iri2012/00_iri2012.tar did not work, attempting backup urls...
Trying: https://github.com/timduly4/pyglow/raw/master/static/00_iri2012.tar
Wrote: ./dl_models/iri12/00_iri2012.tar
time to tar...
tar -xvf ./dl_models/iri12/00_iri2012.tar -C ./dl_models/iri12/
00readme.txt
apf107.dat
ccir11.asc
ccir12.asc
ccir13.asc
ccir14.asc
ccir15.asc
ccir16.asc
ccir17.asc
ccir18.asc
ccir19.asc
ccir20.asc
ccir21.asc
ccir22.asc
cira.for
dgrf1945.dat
dgrf1950.dat
dgrf1955.dat
dgrf1960.dat
dgrf1965.dat
dgrf1970.dat
dgrf1975.dat
dgrf1980.dat
dgrf1985.dat
dgrf1990.dat
dgrf1995.dat
dgrf2000.dat
dgrf2005.dat
igrf2010.dat
igrf2010s.dat
igrf.for
ig_rz.dat
ig_rz_IPS.dat
ig_rz_SEC.dat
iridreg.for
iriflip.for
irifp3.for
irifun.for
iriorbit.for
iriorbitmax.for
irisub.for
iritec.for
iritest.for
ursi11.asc
ursi12.asc
ursi13.asc
ursi14.asc
ursi15.asc
ursi16.asc
ursi17.asc
ursi18.asc
ursi19.asc
ursi20.asc
ursi21.asc
ursi22.asc
Downloading files for msis at https://github.com/timduly4/pyglow/raw/master/static/nrlmsise00_sub.for
Wrote: ./dl_models/msis/nrlmsise00_sub.for
Downloading files for 00_iri.tar at http://irimodel.org/IRI-2016/00_iri.tar
tar -xvf ./dl_models/iri16/00_iri.tar -C ./dl_models/iri16/
00readme.txt
cira.for
dgrf1945.dat
dgrf1950.dat
dgrf1955.dat
dgrf1960.dat
dgrf1965.dat
dgrf1970.dat
dgrf1975.dat
dgrf1980.dat
dgrf1985.dat
dgrf1990.dat
dgrf1995.dat
dgrf2000.dat
dgrf2005.dat
dgrf2010.dat
dgrf2015.dat
igrf2020.dat
igrf2020s.dat
igrf.for
iridreg.for
iriflip.for
irifun.for
irirtam.for
irirtam-test.for
irisub.for
iritec.for
iritest.for
mcsat11.dat
mcsat12.dat
mcsat13.dat
mcsat14.dat
mcsat15.dat
mcsat16.dat
mcsat17.dat
mcsat18.dat
mcsat19.dat
mcsat20.dat
mcsat21.dat
mcsat22.dat
Downloading files for 00_ccir-ursi.tar at http://irimodel.org/COMMON_FILES/00_ccir-ursi.tar
tar -xvf ./dl_models/iri16/00_ccir-ursi.tar -C ./dl_models/iri16/
ccir11.asc
ccir12.asc
ccir13.asc
ccir14.asc
ccir15.asc
ccir16.asc
ccir17.asc
ccir18.asc
ccir19.asc
ccir20.asc
ccir21.asc
ccir22.asc
ursi11.asc
ursi12.asc
ursi13.asc
ursi14.asc
ursi15.asc
ursi16.asc
ursi17.asc
ursi18.asc
ursi19.asc
ursi20.asc
ursi21.asc
ursi22.asc
Downloading: http://irimodel.org/indices/apf107.dat to ./dl_models/iri16/apf107.dat
Downloading: http://irimodel.org/indices/ig_rz.dat to ./dl_models/iri16/ig_rz.dat
cp ./f2py/igrf11/* ./dl_models/igrf11/
cd ./dl_models/igrf11/; make source
make[1]: Entering directory '/home/mk-laptop/pyglow/src/pyglow/models/dl_models/igrf11'
make patch_igrf11;	
make[2]: Entering directory '/home/mk-laptop/pyglow/src/pyglow/models/dl_models/igrf11'
patch igrf11.f -i igrf11.patch -o igrf11_modified.f
patching file igrf11_modified.f (read from igrf11.f)
make[2]: Leaving directory '/home/mk-laptop/pyglow/src/pyglow/models/dl_models/igrf11'
make sig;
make[2]: Entering directory '/home/mk-laptop/pyglow/src/pyglow/models/dl_models/igrf11'
f2py -m igrf11py -h sig_file.pyf igrf11_modified.f only: igrf11syn : | tee out1
/bin/sh: 1: f2py: not found
make[2]: Leaving directory '/home/mk-laptop/pyglow/src/pyglow/models/dl_models/igrf11'
make patch_sig;
make[2]: Entering directory '/home/mk-laptop/pyglow/src/pyglow/models/dl_models/igrf11'
patch sig_file.pyf -i sig.patch -o sig_file_patched.pyf
patching file sig_file_patched.pyf (read from sig_file.pyf)
Hunk #1 FAILED at 13.
1 out of 1 hunk FAILED -- saving rejects to file sig_file_patched.pyf.rej
Makefile:23: recipe for target 'patch_sig' failed
make[2]: *** [patch_sig] Error 1
make[2]: Leaving directory '/home/mk-laptop/pyglow/src/pyglow/models/dl_models/igrf11'
Makefile:29: recipe for target 'source' failed
make[1]: *** [source] Error 2
make[1]: Leaving directory '/home/mk-laptop/pyglow/src/pyglow/models/dl_models/igrf11'
Makefile:25: recipe for target 'source' failed
make: *** [source] Error 2
Plea

**Comment by zfb132** [comment]
From the line `/bin/sh: 1: f2py: not found`, I wonder whether you installed and configured the `numpy` or not.  
In my Ubuntu 20.04, I would add the directory `/home/${USER}/.local/bin` to `PATH` after `pip install numpy --upgrade` because the `f2py` command was installed into `~/.local/bin` default.  
I hope this will help.

**Comment by mkmohamed** [comment]
Thank you zfb132 for your response ans yes it was the path of f2py; when i export the directory .local/bin to PYTHONPATH it works.....wow thank you
