### ISSUE TITLE
IRI not working for future dates

### ISSUE THREAD

**Issue by jhughes-space** [timduly4/pyglow#143]
Hello, I am running version 2.2 of pyglow and unable to get it to compute electron density for future dates. Here is a minimal working example which computes the electron density at 300 km at 0 lat, 0 lon for three days prior and 3 days after today. Ne is -1 for all times past today's date. I think I am assigning the indices correctly. Thanks in advance!

t0 = datetime.datetime.now()
dts = [t0 + datetime.timedelta(hours=x) for x in range(-3*24, 3*24)]

ne = np.zeros(len(dts))

for i in range(len(dts)):
    pt = pyglow.Point(dts[i], 0, 0, 300, user_ind = True)
    pt.f107 = 100
    pt.f107a = 100
    pt.run_iri(version = 2016)
    ne[i] = pt.ne

**Comment by bharding512** [comment]
I am seeing failure on all times >= 2021-12-01 00:00 UT. It also affects ion density and temperature. I will look into this further hopefully within the week.

**Comment by bharding512** [comment]
When I use a fresh install of pyglow, it works fine. Does that fix it for you too?

I'm not sure what happened, but I'm inclined to close this if so.

**Comment by jhughes-space** [comment]
Hey, thanks for reaching out. I will go ahead and try to uninstall and then start over, but that may take some time as I’ve messed up my fortran compiler since I last needed to use pyglow. I’d go ahead and close the issue, and if its still a problem with a fresh install I’ll make a new issue

Joe Hughes, PhD
Research Scientist
Orion Space Solutions
***@***.***

**Comment by bharding512** [comment]
Ok that seems reasonable.
