### ISSUE TITLE
Test example

### ISSUE THREAD

**Issue by aburrell** [timduly4/pyglow#17]
The new output includes dst and ae, while the example does not.

**Comment by timduly4** [comment]
@aburrell , I am thinking of modifying the `Test / Example` section from the README to point to Python scripts located in `./tests`.  It may be more instructive to have a variety of short examples to see how to use pyglow. Thoughts?

**Comment by aburrell** [comment]
I think that’s a good idea.  A series of tests is usually better to help a new user figure out the full strength of a module.
