### ISSUE TITLE
IGRF output mixes up Bx and By

### ISSUE THREAD

**Issue by aburrell** [timduly4/pyglow#18]
After running the test, I saw that Bx and By were swapped.  This should also be changed in the test example, but even with the warning that appears when running IGRF this can be confusing because x,y,z are different in the online version of IGRF12.  Perhaps the point output string could look something like:

From IGRF (+x = E, +y = N, +z = up):
--------------------------------------
     (Bx, By, Bz) = (-6.433e-07, 2.448e-05, -9.925e-06)
                B = 2.643e-05
              dip = 22.06

**Comment by timduly4** [comment]
We changed the vector directions of IGRF to match "East North Up" convention: https://github.com/timduly4/pyglow/blob/master/pyglow/pyglow.py#L436.

Let's address how we should provide examples in https://github.com/timduly4/pyglow/issues/17
