### ISSUE TITLE
IGRF returns x,y,z --> northward, eastward, downward, which is inconsistent with HWM

### ISSUE THREAD

**Issue by timduly4** [timduly4/pyglow#2]
I believe we are all used to ENU (east, north, up) coordinates (i.e., with HWM), but IGRF returns x,y,z --> northward, eastward, downward, which may lead to confusion when using the IGRF model.

I recommend changing this at ~L 292 of pyglow/pyglow.py (here: https://github.com/timduly4/pyglow/blob/master/pyglow/pyglow.py#L292 ), something like:

    Bx = y/1e9 # [T] (positive eastward) (note x/y switch here)
    By = x/1e9 # [T] (positive northward) (note x/y switch here)
    Bz =-z/1e9 # [T] (positive upward) (note negation here)

**Comment by bharding512** [comment]
Totally agree. Let's remember to communicate this to people. Hopefully they're using the trace functions (which we'll also have to change) instead of using the fields directly.

**Comment by timduly4** [comment]
I finally made some time to implement this change.  Please see https://github.com/timduly4/pyglow/commit/62d9a0f743fc38572936c4ceffe3bd4846540b85 for details on what was changed.

I added a warning about the coordinate change within run_igrf method.  The warning will appear only once per session, but I think it is sufficient to let the user know:

    In [6]: pt.run_igrf()
    pyglow/pyglow.py:303: UserWarning: Caution: IGRF coordinates have been recently changed to
     Bx -> positive eastward
     By -> positive northward
     Bz -> positive upward

Thoughts?

**Comment by bharding512** [comment]
Great, thanks Tim. Good idea with the warning. I'll shoot Matt and Jonathan
an email b/c I know they use IGRF a lot.

**Comment by timduly4** [comment]
Sounds good!
