### ISSUE TITLE
IRI runtime for profiles

### ISSUE THREAD

**Issue by aburrell** [timduly4/pyglow#20]
When I use IRI I usually want electron density profiles over the globe.  I've done it with pyglow, but it introduces a significant amount of unnecessary overhead.  Is there an effective method to do this that I didn't see?

**Comment by aburrell** [comment]
So I wrote up a Profile class that may have fixed this.  I'm testing it now, so we'll see how that goes.

**Comment by aburrell** [comment]
It's looking good.  Using timeit to test, the profile takes 5.952862977981567 usec (only 1 loop tested) to return iri density profiles between 80-640 km with a resolution of 7.5˚x3˚ lon x lat over the globe, while doing this using the point class takes 159.10251784324646 usec (only 1 loop tested)

**Comment by aburrell** [comment]
Addressed in #22

**Comment by timduly4** [comment]
@butala implemented a fast(er) calling IRI method:

https://github.com/timduly4/pyglow/pull/12
