### ISSUE TITLE
ImportError: cannot import name 'Point'

### ISSUE THREAD

**Issue by praju05** [timduly4/pyglow#23]
run test_airglow.py

ImportErrorTraceback (most recent call last)
/Users/anaconda3/tutorial/test_airglow.py in <module>()
      3 import numpy as np
      4 
----> 5 from pyglow.pyglow import Point
      6 
      7 # Inputs:

ImportError: cannot import name 'Point'

**Comment by timduly4** [comment]
I believe this is an installation issue.

**Comment by elengul** [comment]
I'm getting this, too.  What do you think could have gone wrong in the installation that would cause this error?

**Comment by bharding512** [comment]
If you can provide a copy of the terminal output during installation, that
may be able to help us help you.

Brian
