### ISSUE TITLE
.so file doesn't exist 

### ISSUE THREAD

**Issue by ELMOUNCHARIH** [timduly4/pyglow#26]
i try to Download the climatological models and wrap them with f2py, but when i check that *.so file exist in each of the ./models/dl_models/<model>/ directories i don't find it

**Comment by timduly4** [comment]
This is most likely a compilation error (i.e., you do not have gfortran). Do you have the transcripts of installing?

**Comment by ELMOUNCHARIH** [comment]
yeah Timothy i install gfortran and it's good thank you :)


*EL MOUNCHARIH ABDELKARIM*

*Étudiant du LPHEA*

*Faculté des Sciences Semlalia*

*Marrakech-Maroc*

2017-05-05 14:13 GMT+01:00 Timothy Duly <notifications@github.com>:

**Comment by timduly4** [comment]
Great!  Ideally we would have a check to make sure `gfortran` is installed.  We can look into implementing this.
