### ISSUE TITLE
gcc error

### ISSUE THREAD

**Issue by bharding512** [timduly4/pyglow#27]
We're trying to install this on Mac OSX 10.11 and are getting the following gcc error:

error: Command "gcc -fno-strict-aliasing -I/Users/jianqiqin/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/tmp/tmppxULvT/src.macosx-10.7-x86_64-2.7 -I/Users/jianqiqin/anaconda/lib/python2.7/site-packages/numpy/core/include -I/Users/jianqiqin/anaconda/include/python2.7 -c /tmp/tmppxULvT/src.macosx-10.7-x86_64-2.7/fortranobject.c -o /tmp/tmppxULvT/tmp/tmppxULvT/src.macosx-10.7-x86_64-2.7/fortranobject.o" failed with exit status 1

No .so files are created. This appears to be the first error. He has f2py, gcc, gfortran. Any ideas? Thanks.

**Comment by timduly4** [comment]
Couple of things to try:

Compare versions of `gcc`, `gfortran`, against working versions: is it as you expect?  I typically use `homebrew` to install these executables.  

Also, I haven't used Anaconda-- maybe that's causing the issue. In principle, however, `pyglow` should work with Anaconda, so we should look into fixing if that is indeed the issue.

**Comment by bharding512** [comment]
He solved the problem. Here is his note:

"Apparently, Anaconda is not the problem. It is because gcc and gfortran were installed in a directory that probably could not be recognized by pyglow. I uninstalled everything that are related to gfortran and gcc, then reinstalled them (using a .dmg file downloaded from gcc.gnu.org).

Also, I installed it with the command "sudo ./pyglow_install.sh", as suggested by Mark this afternoon."

**Comment by timduly4** [comment]
Thanks.  For what it's worth, I use Apple's `gcc`:

```
~ $ which gcc
/usr/bin/gcc
~ $ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
