### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by jswoboda** [timduly4/pyglow#30]
Does Pyglow have a paper or DOI that can be cited?

**Comment by bharding512** [comment]
No, but we may be hearing about some ideas to do this in Yolanda's talk tomorrow.

For now, we just request an acknowledgment, for example: "This work uses pyglow, a Python package that wraps several upper atmosphere climatological models. The pyglow package is open-sourced and available at https://github.com/timduly4/pyglow/."
