### ISSUE TITLE
invalid literal for int() on Windows

### ISSUE THREAD

**Issue by bzossi** [timduly4/pyglow#32]
When I import Pyglow, try to generate geophysical indices table
An error appears in generate_kpap.py line 281
`year = int(fn.split("/")[-1][:4])`

ValueError: invalid literal for int() with base 10: 'ae\\1'

How can I solve this problem?

**Comment by timduly4** [comment]
Hi @bzossi , 

Can you confirm that this problem exists on Linux?

Thanks,
Tim

**Comment by bzossi** [comment]
Hi @timduly4, 

The problem does not exist on linux.
 
I recently began with python, it is hard to me follow the problem among so many new commands.

**Comment by timduly4** [comment]
@bzossi , unfortunately I do not have the bandwidth to support Windows. I would recommend investing running an Ubuntu Linux [Docker container](https://www.docker.com/) on your machine for pyglow.
