### ISSUE TITLE
"import pyglow" doesn't work in pyglow directory

### ISSUE THREAD

**Issue by bharding512** [timduly4/pyglow#33]
Probably just a corner case for PYGLOW_PATH (line 86) in generate_kpap.py. Set it to "." instead of ""

**Comment by bharding512** [comment]
Closed because I can't recreate the problem. If someone can, let me know.

**Comment by timduly4** [comment]
Any chance you were importing from the `pyglow` directory you were using for compiling/installing?

**Comment by bharding512** [comment]
Ah, yes, that's actually why I couldn't recreate the problem, thanks! The problem is when you are in the installation directory (for me, `~/.local/lib/python2.7/site-packages/pyglow`), you can't "import pyglow". I think I can fix this quickly

**Comment by timduly4** [comment]
PS you could do it with this one liner: `PYGLOW_PATH = os.path.dirname(__file__) or './'` 😉
