### ISSUE TITLE
representing Point as string is broken

### ISSUE THREAD

**Issue by bharding512** [timduly4/pyglow#36]
The result of testPyglow.py is

After running models:
<pyglow.pyglow.Point object at 0x7fcb2089f710>

**Comment by bharding512** [comment]
Seems that this was possibly intentional. @timduly4, do you remember why you removed the `pt.__repr__()` function?

https://github.com/timduly4/pyglow/commit/b5fc5842a26d8173de87d5c07b6942a07024036e#diff-eeeee602698c95984cecaab556cd139aL90

**Comment by timduly4** [comment]
@bharding512 this was part of my general cleanup.  I'm not against having a `__repr__()`, but maybe we can do it better then how I had it-- with the "version" of each model (IGRF, HWM, IRI, etc.), we could write a neat table describing member data...

**Comment by timduly4** [comment]
Addressed in https://github.com/timduly4/pyglow/issues/36

**Comment by timduly4** [comment]
For reference, here is a description of the difference between `__str__` and `__repr__`: 

https://www.geeksforgeeks.org/str-vs-repr-in-python/
