### ISSUE TITLE
 'Point' object has no attribute 'run_hwm93'

### ISSUE THREAD

**Issue by jafulet** [timduly4/pyglow#38]
Hi,

When I ran the tests to verify if pyglow is running correctly I got the following error:
Traceback (most recent call last):
  File "version_keyword_verification.py", line 14, in <module>
    pt.run_hwm93()
AttributeError: 'Point' object has no attribute 'run_hwm93'

What does it mean?

Thanks for you help.

**Comment by timduly4** [comment]
@jafulet 

I believe you are on an outdated branch of `pyglow`-- it looks like this Line 14 is from an older version.  

Run a `git pull` to get to the latest version.

Update the repository, and then you can make sure your `version_keyword_verification.py` matches this: https://github.com/timduly4/pyglow/blob/master/tests/test_version_keywords.py

**Comment by jafulet** [comment]
It is running Pyglow. Thank you very much for your support, it's really
appreciated.

With the kindest regards,
Javier

**Comment by timduly4** [comment]
Javier,

Great to hear-- glad it works.

Take care,
Tim
