### ISSUE TITLE
msis flags

### ISSUE THREAD

**Issue by horsley1** [timduly4/pyglow#46]
Hi,
I am running the msis model and can't figure out how to set the flags for the model. Can i do this using the Point user interface?
Matt

**Comment by timduly4** [comment]
@horsley1 , which flags?  I believe you could only modify `f107a`, `f107p`, and `apmsis` currently.

Tim

**Comment by horsley1** [comment]
in the pyglow/pyglow/models/dl_models/miss directory, there is the nrlmsis fortran code, nrlmsise00_sub.for

beginning at line 114 they describe an array that is 23 elements long containing 0/1 values that the user can set, they call them switches (I called them flags by mistake).

**Comment by timduly4** [comment]
@horsley1 , Unfortunately we don't have those MSIS switches implemented yet-- I suppose you could set them before compiling MSIS with `f2py`, but unfortunately there is no way to set them dynamically.
