### ISSUE TITLE
automatically update_indices() when installing

### ISSUE THREAD

**Issue by bharding512** [timduly4/pyglow#6]
Right now, we rely on the new user to read the notes very carefully and call pyglow.update_indices() before they do anything. Ideally, the installation should call pyglow.update_indices()

I believe Dan took a quick look at this, but couldn't figure out how to get it to download the files to the installation location instead of the download location.

**Comment by timduly4** [comment]
Let's use Dan's suggestions and put the following command in `./pyglow_install.sh` (slightly modified)

`cd ~/; python -c "from pyglow import pyglow; pyglow.update_indices()" `
