### ISSUE TITLE
hwm07 patch fail

### ISSUE THREAD

**Issue by jklenzing** [timduly4/pyglow#62]
I'm getting the following errors when trying to install hwm07:

$ patch hwm07e_unix.f90 -i hwm07e.patch -o hwm07e_modified.f90
patching file hwm07e_unix.f90
Hunk #3 FAILED at 159.
Hunk #4 FAILED at 206.
Hunk #6 FAILED at 213.
3 out of 20 hunks FAILED -- saving rejects to file hwm07e_modified.f90.rej

Running on a mac os 10.13.6
patch version 2.5.8

**Comment by timduly4** [comment]
@jklenzing are you in the latest commit?  This was an issue a few weeks ago but has since been resolved. 

```
~/pyglow $ git branch -v
* master 9829acc updated f2py instructions (#59)
```

**Comment by jklenzing** [comment]
On the latest commit (9829acc).  Switching to patch version 2.7.6, I get

patching file hwm07e_modified.f90 (read from hwm07e_unix.f90)
patch: **** '<' followed by space or tab expected at line 16 of patch

**Comment by timduly4** [comment]
patch version 2.7.6? I don't quite follow...

**Comment by jklenzing** [comment]
The version of the patch command

patch -v

**Comment by timduly4** [comment]
@jklenzing , I have the following version of `patch`:
```
~ $ patch --version
patch 2.5.8
Copyright (C) 1988 Larry Wall
Copyright (C) 2002 Free Software Foundation, Inc.
```

**Comment by timduly4** [comment]
@jklenzing I've also tried it in Ubuntu Linux with no issues.  Here's the version of `patch` within Ubuntu Linux:

```
root@8186f4212804:~# patch --version
GNU patch 2.7.5
Copyright (C) 2003, 2009-2012 Free Software Foundation, Inc.
Copyright (C) 1988 Larry Wall
```

**Comment by timduly4** [comment]
@jklenzing Did you ever resolve this issue?
