### ISSUE TITLE
Failing to install pyglow

### ISSUE THREAD

**Issue by RobertoMantas** [timduly4/pyglow#63]
I run "git clone git://github.com/timduly4/pyglow.git pyglow" and everything works fine. Then I "cd pyglow" and after that, I run "make -C src/pyglow/models source" but there it pops up an error saying:

touch ./dl_models/hwm07/dummy.txt
touch ./dl_models/hwm93/dummy.txt
touch ./dl_models/igrf11/dummy.txt
touch ./dl_models/igrf12/dummy.txt
touch ./dl_models/iri12/dummy.txt
touch ./dl_models/iri16/dummy.txt
touch ./dl_models/msis/dummy.txt
python get_models.py
Traceback (most recent call last):
  File "get_models.py", line 3, in <module>
    from future import standard_library
ImportError: No module named future
make: *** [download] Error 1

I already installed "pip install future" so I don't know what is missing. I have also installed gfortran and f2py. 
I would really appreciate your help with this issue so I can start using this tool.
Thank you for your work

**Comment by timduly4** [comment]
@RobertoMantas It looks like your installation of `future` is the problem-- your `pip` could be installing it under python3, or some other strange location.  You can test a successful installation of `future` with:

```
 $ python -c "import future"
```

What do you receive?

**Comment by RobertoMantas** [comment]
If I put $ python -c "import future", I receive:
-----
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named future
-----
But if I put $ python3.6 -c "import future", it is recognized. 
When I write pip list or oio3 list on both lists it appears "future             0.17.1"   
How could I resolve this? Thank you in advance

**Comment by timduly4** [comment]
Right, so it's installed under python3, which is what we suspected.

Try installing under python2.7 via:

```
$ pip2.7 install future --user
```

**Comment by RobertoMantas** [comment]
I get back, -bash: pip2.7: command not found
both pip and pip3 go to the python3.6 folder. 
because if I try either with pip or pip3 it says: 
Requirement already satisfied: future in /sw/lib/python3.6/site-packages (0.17.1)
Thank you

**Comment by timduly4** [comment]
Since this is an issue with installing `future` into the correct python 2/3, I'll close for now.  Thanks.

**Comment by RobertoMantas** [comment]
I solved it! With "python -m pip" will directly look for the pip on that version of python. If I would put python3 -m pip it would work in the pip for python3. As I needed for python2.7 with "python -m pip install future" it worked the installation!
Thank you
