### ISSUE TITLE
Installation on windows

### ISSUE THREAD

**Issue by heinerasmus** [timduly4/pyglow#8]
Hi,

is there an easy way to get the package run on windows machines?

Regards,
Heiner

**Comment by scienceopen** [comment]
Expanding upon what I wrote on the [f2py for Windows page](https://scivision.co/f2py-running-fortran-code-in-python-on-windows/), in general for Windows users and such programs, to save a great deal of time and effort they should consider any one of:

1. using [Windows Subsystem for Linux](https://msdn.microsoft.com/en-us/commandline/wsl/faq)
2. using a virtual machine with Ubuntu  
3. Cygwin

**Comment by timduly4** [comment]
I've never tested it in Windows, but would recommend following @scienceopen 's advice.

As long as you have a gfortran compiler and f2py on your windows shell (e.g., cygwin), I would think you could run this package.

**Comment by heinerasmus** [comment]
I managed to download and wrap the models with cygwin. Windows user also have to modify the path names in the setup.py. Replace the '/' by '\\'. Thanks for the advices.

**Comment by timduly4** [comment]
Thanks.  I'd be curious to know if the python setup has capabilities to automatically install on windows, rather than a burdensome find & replace.  (I'm sure it's a common issue!)

**Comment by heinerasmus** [comment]
I still have some trouble to run the example which is also caused by the different path name handling. I will give an update if can manage to get it run windows.

**Comment by timduly4** [comment]
For example, with IRI, you change directories to the where the IRI data files are located:

https://github.com/timduly4/pyglow/blob/master/pyglow/pyglow.py#L167

I'd imagine this would cause an issue on Windows...

**Comment by scienceopen** [comment]
@timduly4 yes for https://github.com/timduly4/pyglow/blob/master/pyglow/pyglow.py#L167 there is definitely factory functions to do that in os.path in a platform-independent way.

I have not had problems with native Windows or Cygwin just using '/' as separator, only using os.path.join for didactic purposes (in fact, now I universally use Pathlib). However for unexpected usages as in the link above I can see where @heinerasmus and others on Windows would definitely have problems.

**Comment by sterfrag** [comment]
Sorry for reopening issue #8, but as i am new in python and programming in general, could you provide a step by step guide in order to install pyglow on a windows platform? I have already installed gfortran compiler through TDM-GCC platform.

Thanks in andvance for any help you may provide
