### ISSUE TITLE
Failed to wrap models

### ISSUE THREAD

**Issue by samshidler** [timduly4/pyglow#86]
Hi,

I'm trying to install pyglow but the process fails when wrapping the models. I have the following packages/OS:

macOS Mojave: 10.14.2
gfortran: GNU Fortran (GCC) 8.2.0
numpy: 1.16.0
future: 0.17.1
dateutil: 2.6.1

I get the following errors at the "_make all_" step:

$ cd pyglow/src/pyglow/models/
$ make all
rm -rf *~
rm -rf ./dl_models/hwm93/*
rm -rf ./dl_models/hwm07/*
rm -rf ./dl_models/hwm14/*.pyf
rm -rf ./dl_models/hwm14/out*
rm -rf ./dl_models/hwm14/*.so
rm -rf ./dl_models/igrf11/*
rm -rf ./dl_models/igrf12/*
rm -rf ./dl_models/iri12/*
rm -rf ./dl_models/iri16/*
rm -rf ./dl_models/msis/*
touch ./dl_models/hwm07/dummy.txt
touch ./dl_models/hwm93/dummy.txt
touch ./dl_models/igrf11/dummy.txt
touch ./dl_models/igrf12/dummy.txt
touch ./dl_models/iri12/dummy.txt
touch ./dl_models/iri16/dummy.txt
touch ./dl_models/msis/dummy.txt
python get_models.py
Downloading files for igrf11 at http://www.ngdc.noaa.gov/IAGA/vmod/igrf11.f
http://www.ngdc.noaa.gov/IAGA/vmod/igrf11.f did not work, attempting backup urls...
Trying: https://github.com/timduly4/pyglow/raw/master/static/igrf11.f
Wrote: ./dl_models/igrf11/igrf11.f
Downloading files for igrf12 at http://www.ngdc.noaa.gov/IAGA/vmod/igrf12.f
http://www.ngdc.noaa.gov/IAGA/vmod/igrf12.f did not work, attempting backup urls...
Trying: https://github.com/timduly4/pyglow/raw/master/static/igrf12.f
Wrote: ./dl_models/igrf12/igrf12.f
Downloading files for hwm07 at https://github.com/timduly4/pyglow/raw/master/static/HWM07_all_files.zip
Wrote: ./dl_models/hwm07/HWM07_all_file.zip
unzip ./dl_models/hwm07/HWM07_all_file.zip
Archive:  ./dl_models/hwm07/HWM07_all_file.zip
  inflating: HWM07/apexcord.f90      
  inflating: HWM07/apexgrid.dat      
  inflating: HWM07/checkhwm07.f90    
  inflating: HWM07/dwm07b.f90        
  inflating: HWM07/dwm07b_104i.dat   
  inflating: HWM07/hwm071308e.dat    
  inflating: HWM07/hwm07e.f90        
  inflating: HWM07/makefile.g95      
  inflating: HWM07/makefile.ifort    
  inflating: HWM07/readme.txt        
Downloading files for hwm93 at https://github.com/timduly4/pyglow/raw/master/static/hwm93.f
Wrote: ./dl_models/hwm93/hwm93.f
Downloading files for iri12 at http://spdf.gsfc.nasa.gov/pub/models/iri/iri2012/00_iri2012.tar
http://spdf.gsfc.nasa.gov/pub/models/iri/iri2012/00_iri2012.tar did not work, attempting backup urls...
Trying: https://github.com/timduly4/pyglow/raw/master/static/00_iri2012.tar
Wrote: ./dl_models/iri12/00_iri2012.tar
time to tar...
tar -xvf ./dl_models/iri12/00_iri2012.tar -C ./dl_models/iri12/
x 00readme.txt
x apf107.dat
x ccir11.asc
x ccir12.asc
x ccir13.asc
x ccir14.asc
x ccir15.asc
x ccir16.asc
x ccir17.asc
x ccir18.asc
x ccir19.asc
x ccir20.asc
x ccir21.asc
x ccir22.asc
x cira.for
x dgrf1945.dat
x dgrf1950.dat
x dgrf1955.dat
x dgrf1960.dat
x dgrf1965.dat
x dgrf1970.dat
x dgrf1975.dat
x dgrf1980.dat
x dgrf1985.dat
x dgrf1990.dat
x dgrf1995.dat
x dgrf2000.dat
x dgrf2005.dat
x igrf2010.dat
x igrf2010s.dat
x igrf.for
x ig_rz.dat
x ig_rz_IPS.dat
x ig_rz_SEC.dat
x iridreg.for
x iriflip.for
x irifp3.for
x irifun.for
x iriorbit.for
x iriorbitmax.for
x irisub.for
x iritec.for
x iritest.for
x ursi11.asc
x ursi12.asc
x ursi13.asc
x ursi14.asc
x ursi15.asc
x ursi16.asc
x ursi17.asc
x ursi18.asc
x ursi19.asc
x ursi20.asc
x ursi21.asc
x ursi22.asc
Downloading files for msis at https://github.com/timduly4/pyglow/raw/master/static/nrlmsise00_sub.for
Wrote: ./dl_models/msis/nrlmsise00_sub.for
tar -xvf ./dl_models/iri16/00_iri2016.tar -C ./dl_models/iri16/
x 00readme.txt
x cira.for
x dgrf1945.dat
x dgrf1950.dat
x dgrf1955.dat
x dgrf1960.dat
x dgrf1965.dat
x dgrf1970.dat
x dgrf1975.dat
x dgrf1980.dat
x dgrf1985.dat
x dgrf1990.dat
x dgrf1995.dat
x dgrf2000.dat
x dgrf2005.dat
x dgrf2010.dat
x igrf2015.dat
x igrf2015s.dat
x igrf.for
x iridreg.for
x iriflip.for
x irifun.for
x irisub.for
x iritec.for
x iritest.for
x mcsat11.dat
x mcsat12.dat
x mcsat13.dat
x mcsat14.dat
x mcsat15.dat
x mcsat16.dat
x mcsat17.dat
x mcsat18.dat
x mcsat19.dat
x mcsat20.dat
x mcsat21.dat
x mcsat22.dat
tar -xvf ./dl_models/iri16/00_ccir-ursi.tar -C ./dl_models/iri16/
x ccir11.asc
x ccir12.asc
x ccir13.asc
x ccir14.asc
x ccir15.asc
x ccir16.asc
x ccir17.asc
x ccir18.asc
x ccir19.asc
x ccir20.asc
x ccir21.asc
x ccir22.asc
x ursi11.asc
x ursi12.asc
x ursi13.asc
x ursi14.asc
x ursi15.asc
x ursi16.asc
x ursi17.asc
x ursi18.asc
x ursi19.asc
x ursi20.asc
x ursi21.asc
x ursi22.asc
Downloading: http://irimodel.org/indices/apf107.dat to ./dl_models/iri16/apf107.dat
Downloading: http://irimodel.org/indices/ig_rz.dat to ./dl_models/iri16/ig_rz.dat
cp ./f2py/igrf11/* ./dl_models/igrf11/
cd ./dl_models/igrf11/; make source
make patch_igrf11;	
patch igrf11.f -i igrf11.patch -o igrf11_modified.f
patching file igrf11.f
make sig;
f2py -m igrf11py -h sig_file.pyf igrf11_modified.f only: igrf11syn : | tee out1
Reading fortran codes...
	Reading file 'igrf11_modified.f' (format:fix,strict)
Post-processing...
	Block: igrf11py
{}
In: :igrf11py:igrf11_modified.f:igrf11syn
vars2fortran: No typespec for argument "isv".
{}
In: :igrf11py:igrf11_modified.f:igrf11syn
vars2fortran: No typespec for argument "date".
{}
In: :igrf11py:igrf11_modified.f:igrf11syn
vars2fortran: No typespec for argument "itype".
{}
In: :igrf11py:igrf11_modified.f:igrf11syn
vars2fortran: No typespec for argument "alt".
{}
In: :igrf11py:igrf11_modified.f:igrf11syn
vars2fortran: No typespec for argument "colat".
{}
In: :igrf11py:igrf11_modified.f:igrf11syn
vars2fortran: No typespec for argument "elong".
{}
In: :igrf11py:igrf11_modified.f:igrf11syn
vars2fortran: No typespec for argument "x".
{}
In: :igrf11py:igrf11_modified.f:igrf11syn
vars2fortran: No typespec for argument "y".
{}
In: :igrf11py:igrf11_modified.f:igrf11syn
vars2fortran: No typespec for argument "z".
{}
In: :igrf11py:igrf11_modified.f:igrf11syn
vars2fortran: No typespec for argument "f".
			Block: igrf11syn
Post-processing (stage 2)...
Saving signatures to file "./sig_file.pyf"
make patch_sig;
patch sig_file.pyf -i sig.patch -o sig_file_patched.pyf
patching file sig_file.pyf
cp ./f2py/igrf12/* ./dl_models/igrf12/
cd ./dl_models/igrf12/; make source
make patch_igrf12;	
patch igrf12.f -i igrf12.patch -o igrf12_modified.f
patching file igrf12.f
make sig;
f2py -m igrf12py -h sig_file.pyf igrf12_modified.f only: igrf12syn : | tee out1
Reading fortran codes...
	Reading file 'igrf12_modified.f' (format:fix,strict)
Post-processing...
	Block: igrf12py
{}
In: :igrf12py:igrf12_modified.f:igrf12syn
vars2fortran: No typespec for argument "isv".
{}
In: :igrf12py:igrf12_modified.f:igrf12syn
vars2fortran: No typespec for argument "date".
{}
In: :igrf12py:igrf12_modified.f:igrf12syn
vars2fortran: No typespec for argument "itype".
{}
In: :igrf12py:igrf12_modified.f:igrf12syn
vars2fortran: No typespec for argument "alt".
{}
In: :igrf12py:igrf12_modified.f:igrf12syn
vars2fortran: No typespec for argument "colat".
{}
In: :igrf12py:igrf12_modified.f:igrf12syn
vars2fortran: No typespec for argument "elong".
{}
In: :igrf12py:igrf12_modified.f:igrf12syn
vars2fortran: No typespec for argument "x".
{}
In: :igrf12py:igrf12_modified.f:igrf12syn
vars2fortran: No typespec for argument "y".
{}
In: :igrf12py:igrf12_modified.f:igrf12syn
vars2fortran: No typespec for argument "z".
{}
In: :igrf12py:igrf12_modified.f:igrf12syn
vars2fortran: No typespec for argument "f".
			Block: igrf12syn
Post-processing (stage 2)...
Saving signatures to file "./sig_file.pyf"
make patch_sig;
patch sig_file.pyf -i sig.patch -o sig_file_patched.pyf
patching file sig_file.pyf
cp -v ./f2py/msis/* ./dl_models/msis/
./f2py/msis/Makefile -> ./dl_models/msis/Makefile
./f2py/msis/nrlmsise00_sub.patch -> ./dl_models/msis/nrlmsise00_sub.patch
./f2py/msis/sig.patch -> ./dl_models/msis/sig.patch
cd ./dl_models/msis/; make source;
make patch_msis;
patch nrlmsise00_sub.for -i nrlmsise00_sub.patch -o nrlmsise00_sub_patched.for
patching file nrlmsise00_sub.for
make sig;
f2py -m msis00py -h sig_file.pyf nrlmsise00_sub_patched.for only: gtd7 : | tee out1
rmbadname1: Replacing "long" with "long_bn".
rmbadname1: Replacing "long" with "long_bn".
rmbadname1: Replacing "long" with "long_bn".
Reading fortran codes...
	Reading file 'nrlmsise00_sub_patched.for' (format:fix,strict)
Post-processing...
	Block: msis00py
{}
In: :msis00py:nrlmsise00_sub_patched.for:gtd7
vars2fortran: No typespec for argument "iyd".
{}
In: :msis00py:nrlmsise00_sub_patched.for:gtd7
vars2fortran: No typespec for argument "sec".
{}
In: :msis00py:nrlmsise00_sub_patched.for:gtd7
vars2fortran: No typespec for argument "alt".
{}
In: :msis00py:nrlmsise00_sub_patched.for:gtd7
vars2fortran: No typespec for argument "glat".
{}
In: :msis00py:nrlmsise00_sub_patched.for:gtd7
vars2fortran: No typespec for argument "glong".
{}
In: :msis00py:nrlmsise00_sub_patched.for:gtd7
vars2fortran: No typespec for argument "stl".
{}
In: :msis00py:nrlmsise00_sub_patched.for:gtd7
vars2fortran: No typespec for argument "f107a".
{}
In: :msis00py:nrlmsise00_sub_patched.for:gtd7
vars2fortran: No typespec for argument "f107".
{'attrspec': ['dimension(7)']}
In: :msis00py:nrlmsise00_sub_patched.for:gtd7
vars2fortran: No typespec for argument "ap".
{}
In: :msis00py:nrlmsise00_sub_patched.for:gtd7
vars2fortran: No typespec for argument "mass".
{'attrspec': ['dimension(9)']}
In: :msis00py:nrlmsise00_sub_patched.for:gtd7
vars2fortran: No typespec for argument "d".
{'attrspec': ['dimension(2)']}
In: :msis00py:nrlmsise00_sub_patched.for:gtd7
vars2fortran: No typespec for argument "t".
			Block: gtd7
			Block: gtd7bk
Post-processing (stage 2)...
Saving signatures to file "./sig_file.pyf"
make patch_sig;
patch sig_file.pyf -i sig.patch -o sig_file_patched.pyf
patching file sig_file.pyf
cp ./f2py/hwm93/* ./dl_models/hwm93/
cd ./dl_models/hwm93/; make source;
patch hwm93.f -i hwm93.patch -o hwm93_modified.f
patching file hwm93.f
f2py -m hwm93py -h sig_file.pyf hwm93_modified.f only: gws5 : | tee out1
rmbadname1: Replacing "long" with "long_bn".
rmbadname1: Replacing "long" with "long_bn".
rmbadname1: Replacing "long" with "long_bn".
rmbadname1: Replacing "long" with "long_bn".
rmbadname1: Replacing "long" with "long_bn".
rmbadname1: Replacing "long" with "long_bn".
analyzevars: character array "character*4 isdate(3)" is considered as "character isdate(3,4)"; "intent(c)" is forced.
analyzevars: character array "character*4 name(2)" is considered as "character name(2,4)"; "intent(c)" is forced.
analyzevars: character array "character*4 istime(2)" is considered as "character istime(2,4)"; "intent(c)" is forced.
Reading fortran codes...
	Reading file 'hwm93_modified.f' (format:fix,strict)
Post-processing...
	Block: hwm93py
{}
In: :hwm93py:hwm93_modified.f:gws5
vars2fortran: No typespec for argument "iyd".
{}
In: :hwm93py:hwm93_modified.f:gws5
vars2fortran: No typespec for argument "sec".
{}
In: :hwm93py:hwm93_modified.f:gws5
vars2fortran: No typespec for argument "alt".
{}
In: :hwm93py:hwm93_modified.f:gws5
vars2fortran: No typespec for argument "glat".
{}
In: :hwm93py:hwm93_modified.f:gws5
vars2fortran: No typespec for argument "glong".
{}
In: :hwm93py:hwm93_modified.f:gws5
vars2fortran: No typespec for argument "stl".
{}
In: :hwm93py:hwm93_modified.f:gws5
vars2fortran: No typespec for argument "f107a".
{}
In: :hwm93py:hwm93_modified.f:gws5
vars2fortran: No typespec for argument "f107".
{'attrspec': ['dimension(1)']}
In: :hwm93py:hwm93_modified.f:gws5
vars2fortran: No typespec for argument "ap".
{'attrspec': ['dimension(2)']}
In: :hwm93py:hwm93_modified.f:gws5
vars2fortran: No typespec for argument "w".
			Block: gws5
			Block: initw5
			Block: gwsbk5
Post-processing (stage 2)...
Saving signatures to file "./sig_file.pyf"
patch sig_file.pyf -i sig.patch -o sig_file_patched.pyf
patching file sig_file.pyf
cp ./f2py/iri12/* ./dl_models/iri12/
cd ./dl_models/iri12/; make source;
make patch_iridreg;
patch iridreg.for -i iridreg.patch -o iridreg_modified.for
patching file iridreg.for
make patch_iriflip;
python delete_iriflip_comments.py
perl -pi -e 's/![\.|-].*$//g' iriflip.for
#patch iriflip.for -i iriflip.patch -o iriflip_modified.for
sed -i 's/cm-3//g' iriflip.for
sed: 1: "iriflip.for": command i expects \ followed by text
make[1]: *** [source] Error 1
make: *** [source] Error 2

**Comment by timduly4** [comment]
@samshidler Thanks-- this is due to running `sed` on mac.  The issue has been fixed (https://github.com/timduly4/pyglow/pull/87)

**Comment by samshidler** [comment]
The previous error is gone but I get a new,

compiling Fortran sources
Fortran f77 compiler: /usr/local/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -arch x86_64 -fPIC -O3 -funroll-loops
Fortran f90 compiler: /usr/local/bin/gfortran -Wall -g -fno-second-underscore -arch x86_64 -fPIC -O3 -funroll-loops
Fortran fix compiler: /usr/local/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -arch x86_64 -fPIC -O3 -funroll-loops
compile options: '-I/var/folders/05/83758__n4zz5936dr78pkfx40000gn/T/tmpN0NkS1/src.macosx-10.6-x86_64-2.7 -I/Users/samshidler/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/Users/samshidler/anaconda2/include/python2.7 -c'
gfortran:f77: igrf11_modified.f
igrf11_modified.f:57:72:

       data g0/ -31543.,-2298., 5922., -677., 2905.,-1061.,  924., 1121., 1900
                                                                        1
Warning: Line truncated at (1) [-Wline-truncation]
igrf11_modified.f:58:72:

      1           1022.,-1469., -330., 1256.,    3.,  572.,  523.,  876., 1900
                                                                        1
Warning: Line truncated at (1) [-Wline-truncation]
igrf11_modified.f:59:72:

      2            628.,  195.,  660.,  -69., -361., -210.,  134.,  -75., 1900
                                                                        1
Warning: Line truncated at (1) [-Wline-truncation]
igrf11_modified.f:60:72:

      3           -184.,  328., -210.,  264.,   53.,    5.,  -33.,  -86., 1900
                                                                        1
Warning: Line truncated at (1) [-Wline-truncation]
igrf11_modified.f:61:72:

      4           -124.,  -16.,    3.,   63.,   61.,   -9.,  -11.,   83., 1900
                                                                        1
Warning: Line truncated at (1) [-Wline-truncation]
igrf11_modified.f:62:72:

      5           -217.,    2.,  -58.,  -35.,   59.,   36.,  -90.,  -69., 1900
                                                                        1
.
.
.
.
.

Warning: Line truncated at (1) [-Wline-truncation]
igrf11_modified.f:453:72:

      6            -1.6,   -0.5,   -0.2,    0.8,    1.8,    0.5,    0.2,  2012
                                                                        1
Warning: Line truncated at (1) [-Wline-truncation]
igrf11_modified.f:454:72:

      7            -0.1,    0.6,   -0.6,    0.3,    1.4,   -0.2,    0.3,  2012
                                                                        1
Warning: Line truncated at (1) [-Wline-truncation]
igrf11_modified.f:455:72:

      8            -0.1,    0.1,   -0.8,   -0.8,   -0.3,    0.4,    0.2,  2012
                                                                        1
Warning: Line truncated at (1) [-Wline-truncation]
igrf11_modified.f:456:72:

      9            -0.1,    0.1,    0.0,   -0.5,    0.2,    0.3,    0.5,  2012
                                                                        1
Warning: Line truncated at (1) [-Wline-truncation]
igrf11_modified.f:457:72:

      a            -0.3,    0.4,    0.3,    0.1,    0.2,   -0.1,   -0.5,  2012
                                                                        1
Warning: Line truncated at (1) [-Wline-truncation]
igrf11_modified.f:458:72:

      b             0.4,    0.2,    0.4,115*0.0/                          2012
                                                                        1
Warning: Line truncated at (1) [-Wline-truncation]
igrf11_modified.f:472:14:

       ll    = t
              1
Warning: Possible change of value in conversion from REAL(8) to INTEGER(4) at (1) [-Wconversion]
igrf11_modified.f:486:15:

        ll    = 0.2*(date - 1995.0)
               1
Warning: Possible change of value in conversion from REAL(8) to INTEGER(4) at (1) [-Wconversion]
igrf11_modified.f:572:0:

        three = (fn + gn)/one
 
Warning: ‘gn’ may be used uninitialized in this function [-Wmaybe-uninitialized]
igrf11_modified.f:557:0:

        fn    = n
 
Warning: ‘fn’ may be used uninitialized in this function [-Wmaybe-uninitialized]
/usr/local/bin/gfortran -Wall -g -arch x86_64 -Wall -g -undefined dynamic_lookup -bundle /var/folders/05/83758__n4zz5936dr78pkfx40000gn/T/tmpN0NkS1/var/folders/05/83758__n4zz5936dr78pkfx40000gn/T/tmpN0NkS1/src.macosx-10.6-x86_64-2.7/igrf11pymodule.o /var/folders/05/83758__n4zz5936dr78pkfx40000gn/T/tmpN0NkS1/var/folders/05/83758__n4zz5936dr78pkfx40000gn/T/tmpN0NkS1/src.macosx-10.6-x86_64-2.7/fortranobject.o /var/folders/05/83758__n4zz5936dr78pkfx40000gn/T/tmpN0NkS1/igrf11_modified.o -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0/../../.. -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0/../../.. -L/Users/samshidler/anaconda2/lib -lgfortran -o ./igrf11py.so
Removing build directory /var/folders/05/83758__n4zz5936dr78pkfx40000gn/T/tmpN0NkS1
cp: igrf11py.*.so: No such file or directory
make: *** [all] Error 1


Looking through the directories, models/dl_models/igrf11/igrf11py.so does exist.

**Comment by timduly4** [comment]
Nothing jumps out at me-- can you post the full log?

**Comment by samshidler** [comment]
Attached is the terminal output.

[pyglow_log.txt](https://github.com/timduly4/pyglow/files/2761722/pyglow_log.txt)

**Comment by timduly4** [comment]
@samshidler I just added this fix (https://github.com/timduly4/pyglow/pull/88)-- git it another try.

**Comment by samshidler** [comment]
I had a previous version of pyglow (Version 1.1) saved under a different folder name. I deleted that and tried again and it worked.

Thank you for your help.

**Comment by timduly4** [comment]
Great to hear @samshidler -- I changed the `copy` command to `rsync` to suppress any issues (https://github.com/timduly4/pyglow/pull/89 ).

**Comment by timduly4** [comment]
I'll close for now, but let me know if you have any other issues.
