### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bharding512** [timduly4/pyglow#9]
pyglow should have a license. CC-BY seems to be the recommended one.

https://creativecommons.org/licenses/

**Comment by timduly4** [comment]
Agreed.  However,  according to https://github.com/github/choosealicense.com/issues/33 , it is not recommended to use a creative commons license.

I can easily add the following licenses on GitHub:

![licenses](https://cloud.githubusercontent.com/assets/2175172/16209296/a066dce6-36f3-11e6-91a6-70ba413903ca.png)

Perhaps the "GNU General Public License v3.0" would be appropriate?

Thoughts?

**Comment by bharding512** [comment]
Interesting. At first glance it looks like this doesn't allow people to use pyglow for commercial purposes (and I'm not sure how it would affect people doing classified work). If we want to allow this, we should at least make sure they still reference the project.

**Comment by timduly4** [comment]
MIT License has been added.
