### ISSUE TITLE
IRI TypeError: failed to initialize intent(inout|inplace|cache) array, input not an array

### ISSUE THREAD

**Issue by bcurtiswx** [timduly4/pyglow#97]
Python 3.7.2 (default, Dec 29 2018, 06:19:36)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information

>from datetime import datetime
>import math
>import unittest
>from pyglow import IRI
>from pyglow import LocationTime
>iri = IRI()
>dn = datetime(2010, 3, 23, 15, 30)
>lat = 30.
>lon = -80.
>alt = 250.
>location_time = LocationTime(dn, lat, lon, alt)
>iri.run(location_time)

Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/bcurtis/.local/lib/python3.7/site-packages/pyglow/iri.py", line 194, in run
oarr,
TypeError: failed to initialize intent(inout|inplace|cache) array, input not an array`

**Comment by timduly4** [comment]
@bcurtiswx do the unit tests for IRI pass?

```
~/pyglow $ pytest test/test_iri.py

============================== test session starts ===============================
platform darwin -- Python 3.7.2, pytest-4.1.1, py-1.6.0, pluggy-0.7.1
rootdir: /Users/duly/pyglow, inifile:
collected 7 items                                                                

test/test_iri.py .......                                                   [100%]

============================ 7 passed in 0.32 seconds ============================
```

**Comment by bcurtiswx** [comment]
I'll be able to test it on the machine with the issue on Monday

**Comment by onallig2** [comment]
Hi, 

I get the same IRI TypeError:

```
~/examples $ python3 test_iri12_iri16.py
Computing alt=100.0 km...
about to run iri pls don't fail...
Traceback (most recent call last):
  File "test_iri12_iri16.py", line 26, in <module>
    pt.run_iri()  # default year is 2016
  File "/Users/onalli/.local/lib/python3.5/site-packages/pyglow/pyglow.py", line 201, in run_iri
    f107a=f107a,
  File "/Users/onalli/.local/lib/python3.5/site-packages/pyglow/iri.py", line 194, in run
    oarr,
TypeError: failed to initialize intent(inout|inplace|cache) array, input not an array
```
As suggested, I run the unit tests for IRI, but they fail and I get the following: 

<img width="1440" alt="Screen Shot 2020-09-10 at 1 57 15 AM" src="https://user-images.githubusercontent.com/42647696/92687221-23da8480-f309-11ea-9a3f-45eba66bd0b1.png">

I have the following packages/OS version:
macOS Catalina: 10.15.6 
gfortran: GNU Fortran (Homebrew GCC 10.2.0) 10.2.0 
numpy: 1.18.5 
future: 0.18.2 
python-dateutil: 2.8.1

Any advice would be greatly appreciated. Thanks for your help.

**Comment by bharding512** [comment]
Closing because the latest IRI release works for me. If this problem remains, please reopen
