### ISSUE TITLE
IRI using BIL-1995 instead of TBT-2012 for electron temperature

### ISSUE THREAD

**Issue by samshidler** [timduly4/pyglow#99]
I'm currently using pyglow version 2.2. 

In iri.py the flag jf[22] is currently set to use TBT-2012 but after plotting the output for electron temperature it appears to be coming from BIL-1995. 

Below is the code I used to generate a longitudinal profile of electron temperature:

from pyglow.pyglow import Point
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np

lat = 0                  # Geographic Latitude
alt = 590                # Altitude
lons = np.arange(0, 360) # Longitudes

dn = datetime(2004, 9, 21, 1, 0) # 1 UT

Te = np.empty(len(lons))

for i, lon in enumerate(lons):
    pt = Point(dn, lat, lon, alt, user_ind=True)
    pt.f107 = 95.6
    pt.f107a = 95.6
    pt.run_iri()
    Te[i] = pt.Te

plt.plot(lons, Te, 'k')
plt.title('Electron Temperatures')
plt.xlabel('Longitude, Degree')
plt.ylabel('Te, K')
plt.ylim(500, 3000)
plt.xlim(0, 400)
plt.xticks([0, 100, 200, 300, 400])
plt.grid()

![Te_pyglow](https://user-images.githubusercontent.com/36082908/54054370-9a944000-41af-11e9-8ab0-c696f26e40bd.png)

I also made the same plot using the IRI ModelWeb (https://ccmc.gsfc.nasa.gov/modelweb/models/iri2016_vitmo.php) with the following settings:
![IRI_settings](https://user-images.githubusercontent.com/36082908/54054498-ee068e00-41af-11e9-9868-8b46f8f78acb.png)

Selecting TBT-2012 for Te Topside produces the following plot:
![Te_TBT-2012](https://user-images.githubusercontent.com/36082908/54054458-d0d1bf80-41af-11e9-847b-6d6038254996.png)

Selecting BIL-1995 for Te Topside produces the following plot:
![Te_BIL-1995](https://user-images.githubusercontent.com/36082908/54054477-de874500-41af-11e9-9f66-c13a713a9324.png)

Changing to jf[22] = 1 appears to be using TBT-2012+SA instead of TBT-2012.

**Comment by timduly4** [comment]
@samshidler can plot the temperatures on the same plot for a better comparison?

What is the standard Te Topside, and what `jf` index does this correspond to?

**Comment by samshidler** [comment]
The IRI Web interface uses TBT-2012 + SA as default.
This corresponds to the jf[22] flag in Python (23 in Fortran).
Here is the output from IRI web for the three different models:
![IRI_web_Te](https://user-images.githubusercontent.com/36082908/55184141-6f25c500-515f-11e9-8330-7890348fc376.png)

Here is the output from Pyglow for jf[22] = 0 and jf[22] = 1:
![Pyglow_Te](https://user-images.githubusercontent.com/36082908/55184192-8ebced80-515f-11e9-9a6d-7d404abfca1f.png)


The IRI documentation says that setting jf[22] = 0 should correspond to TBT-2012 and jf[22] = 1 should correspond to BIL-1995 but I am getting the opposite output.

**Comment by timduly4** [comment]
@samshidler see https://github.com/timduly4/pyglow/pull/101 -- do you agree with the proposed change?

**Comment by samshidler** [comment]
Were you able to replicate the problem? I just want to verify that it's not something on my end.

**Comment by timduly4** [comment]
@samshidler can you provide the steps and scripts I need to reproduce your plots?

**Comment by samshidler** [comment]
To produce the Pyglow plots I used the following:

from pyglow.pyglow import Point
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np

lat = 0 # Geographic Latitude
alt = 590 # Altitude
lons = np.arange(0, 360) # Longitudes

dn = datetime(2004, 9, 21, 1, 0) # 1 UT

Te = np.empty(len(lons))

for i, lon in enumerate(lons):
pt = Point(dn, lat, lon, alt, user_ind=True)
pt.f107 = 95.6
pt.f107a = 95.6
pt.run_iri()
Te[i] = pt.Te

plt.plot(lons, Te, 'k')
plt.title('Electron Temperatures')
plt.xlabel('Longitude, Degree')
plt.ylabel('Te, K')
plt.ylim(500, 3000)
plt.xlim(0, 400)
plt.xticks([0, 100, 200, 300, 400])
plt.grid()

filename = ''
np.save(filename, Te)


I just switched the jf[22] flag and saved the Te arrays and then plotted them on top of each other. For the IRI Web data, I just selected that the output for each of the three Te flags be saved to an ASCII format and then plotted the data in python.

**Comment by samshidler** [comment]
After revisiting this, it appears that the problem was associated with the IRI web page. The IRI Web Page results now correctly match the Pyglow results. The flag jf[22]=0 is correct.
